### ISSUE TITLE
Unable to run docker-compose

### ISSUE THREAD

**Issue by templatedop** [ameerhmzx/hasura-jwt-auth#1]
Hi,

Firstly, let me appreciate for the work done in golang.

I have gone through the code and I am sure it will work fine.

However, when I trying to run docker-compose, it is throwing following error. Request to kindly help me on this.

```
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 67, in main
  File "compose/cli/main.py", line 123, in perform_command
  File "compose/cli/command.py", line 69, in project_from_options
  File "compose/cli/command.py", line 141, in get_project
  File "compose/project.py", line 134, in from_config
  File "compose/project.py", line 910, in translate_deploy_keys_to_container_config
  File "compose/project.py", line 911, in <listcomp>
TypeError: argument of type 'NoneType' is not iterable
[1749] Failed to execute script docker-compose
```

**Comment by ameerhmzx** [comment]
Hi @madugula007 are you using WSL? 
as I tested the docker-compose on my Linux machine and this error seems like a `docker-compose` issue.

make sure `docker` & `docker-compose` is updated.

**Comment by templatedop** [comment]
Hey! Brother 
I am using MacBook.
Os version is bigsur

**Comment by templatedop** [comment]
Hey! 

I was working in docker desktop. 

Docker desktop was closed because of which above error was thrown.


However, I am still error. Graphql Engine is unable to access db.

Logs are furnished below for reference. Please help and guide me.


```
postgres_1        | The files belonging to this database system will be owned by user "postgres".
postgres_1        | This user must also own the server process.
postgres_1        | 
postgres_1        | The database cluster will be initialized with locale "en_US.utf8".
postgres_1        | The default database encoding has accordingly been set to "UTF8".
postgres_1        | The default text search configuration will be set to "english".
postgres_1        | 
postgres_1        | Data page checksums are disabled.
postgres_1        | 
postgres_1        | initdb: error: directory "/var/lib/postgresql/data" exists but is not empty
postgres_1        | It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.
postgres_1        | Using a mount point directly as the data directory is not recommended.
postgres_1        | Create a subdirectory under the mount point.
hasura-jwt-auth_postgres_1 exited with code 1
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-17T06:12:34.687+0000","level":"info","detail":{"kind":"server_configuration","info":{"live_query_options":{"batch_size":100,"refetch_delay":1},"transaction_isolation":"ISOLATION LEVEL READ COMMITTED","plan_cache_options":{"plan_cache_size":4000},"enabled_log_types":["http-log","websocket-log","startup","webhook-log","query-log"],"server_host":"HostAny","enable_allowlist":false,"log_level":"info","auth_hook_mode":null,"use_prepared_statements":true,"unauth_role":"anonymous","stringify_numeric_types":false,"enabled_apis":["metadata","graphql","config","pgdump"],"enable_telemetry":false,"enable_console":true,"auth_hook":null,"jwt_secret":{"audience":null,"claims_format":"json","claims_namespace":"https://hasura.io/jwt/claims","jwk_url":"http://actions:8081/.well-known/jwks.json","issuer":null},"cors_config":{"allowed_origins":"*","disabled":false,"ws_read_cookie":null},"console_assets_dir":null,"admin_secret_set":true,"port":8080}}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-17T06:12:34.687+0000","level":"info","detail":{"kind":"postgres_connection","info":{"retries":1,"database_url":"postgres://postgres:...@postgres:5432/postgres"}}}
graphql-engine_1  | {"type":"pg-client","timestamp":"2021-02-17T06:12:34.687+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(0)."}}
graphql-engine_1  | {"type":"pg-client","timestamp":"2021-02-17T06:12:34.687+0000","level":"warn","detail":{"message":"postgres connection failed, retrying(1)."}}
graphql-engine_1  | {"type":"startup","timestamp":"2021-02-17T06:12:34.687+0000","level":"error","detail":{"kind":"catalog_migrate","info":{"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}}}
graphql-engine_1  | {"internal":"could not translate host name \"postgres\" to address: Name or service not known\n","path":"$","error":"connection error","code":"postgres-error"}
hasura-jwt-auth_graphql-engine_1 exited with code 1
```
 
Some issue here:
**initdb: error: directory "/var/lib/postgresql/data" exists but is not empty**
postgres_1        | It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.
postgres_1        | Using a mount point directly as the data directory is not recommended.
postgres_1        | Create a subdirectory under the mount point.


Too many Postgres installation happened and I have removed those volumes also. 

Tried `docker volume inspect db` there is no such volume.

Appears to be my laptop issue. Need to clear volumes which are not found.   :)


I changed volume to db:/var/lib/postgresql1/data and presently I am able to access graphql.

Will update you the result.......

**Comment by madugula007** [comment]
Hey!

I am able to generate token with login.

But Hasura says header malformed.

I have added header key as "Authorization"
and  header value key starts with "bearer " space followed by token.

Please guide...

**Comment by templatedop** [comment]
Done it's working.
Thank you.

**Comment by ameerhmzx** [comment]
> Some issue here:
> **initdb: error: directory "/var/lib/postgresql/data" exists but is not empty**
> postgres_1 | It contains a dot-prefixed/invisible file, perhaps due to it being a mount point.
> postgres_1 | Using a mount point directly as the data directory is not recommended.
> postgres_1 | Create a subdirectory under the mount point.
> 
> Too many Postgres installation happened and I have removed those volumes also.
> 
> Tried `docker volume inspect db` there is no such volume.
> 
> Appears to be my laptop issue. Need to clear volumes which are not found. :)
> 
> I changed volume to db:/var/lib/postgresql1/data and presently I am able to access graphql.
> 
> Will update you the result.......

This issue was not with your laptop, but because of the `.gitignore` file in the db folder. 
but docker-compose was not reporting the error clearly.
I updated the instructions accordingly.
